on: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: CocoaPod
          command: pod install
      - run:
          name: Build
          command: xcodebuild build SWIFT_VERSION=4.2 -scheme 'Example' -workspace 'RxAdMob.xcworkspace' -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty -c
